# Lazygit configuration — Zenbones Light theme
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#286486"
      - bold
    inactiveBorderColor:
      - "#CFC1BA"
    selectedLineBgColor:
      - "#CBD9E3"
    searchingActiveBorderColor:
      - "#944927"
      - bold
    optionsTextColor:
      - "#286486"
    cherryPickedCommitBgColor:
      - "#CBD9E3"
    cherryPickedCommitFgColor:
      - "#2C363C"
    unstagedChangesColor:
      - "#A8334C"
    defaultFgColor:
      - "#2C363C"
