# Starship prompt configuration
# Docs: https://starship.rs/config/
# Theme: Zenbones Light

command_timeout = 1000
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$go\
$lua\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = '[>](bold #2C363C)'
error_symbol = '[>](bold #A8334C)'

[directory]
style = 'bold #286486'
truncation_length = 3
truncate_to_repo = true

[git_branch]
style = 'bold #4F6C31'
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = '#A8334C'
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2_000
style = '#88507D'
format = '[$duration]($style) '

[python]
style = '#88507D'
format = '[$symbol$version]($style) '

[nodejs]
style = '#88507D'
format = '[$symbol$version]($style) '

[rust]
style = '#88507D'
format = '[$symbol$version]($style) '

[golang]
style = '#88507D'
format = '[$symbol$version]($style) '

[lua]
style = '#88507D'
format = '[$symbol$version]($style) '
