# Lazygit configuration — Gruvbox Material Light theme
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#45707a"
      - bold
    inactiveBorderColor:
      - "#a89984"
    selectedLineBgColor:
      - "#e5d5ad"
    searchingActiveBorderColor:
      - "#c35e0a"
      - bold
    optionsTextColor:
      - "#45707a"
    cherryPickedCommitBgColor:
      - "#e5d5ad"
    cherryPickedCommitFgColor:
      - "#4f3829"
    unstagedChangesColor:
      - "#c14a4a"
    defaultFgColor:
      - "#654735"
